apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app-v2
  labels:
    app: api-v2
spec:
  replicas: 5
  selector:
    matchLabels:
      app: api-v2
  strategy:
   type: RollingUpdate
   rollingUpdate:
     maxUnavailable: 1
  template:
    metadata:
      labels:
        app: api-v2
    spec:
      containers:
      - name: api-v2
        image: 775698064297.dkr.ecr.eu-west-3.amazonaws.com/abdelhak/simple-app:v0.0
        env:
        - name: ADDR
          value: "redis-0.redis:6379"
        - name: PASSWORD
          value: ""
        - name: VERSION
          value: "v2.0"
        ports:
        - containerPort: 8080
      imagePullSecrets: 
      - name: ecr-helper